version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - zip -r lambda_function.zip .
  post_build:
    commands:
      - aws s3 cp lambda_function.zip s3://your-lambda-deployments-bucket/lambda_function.zip

artifacts:
  files:
    - lambda_function.zip
